CREATE TABLE HR.MEMBER_2
(
	name        VARCHAR2 NOT NULL,
	id          VARCHAR2 NOT NULL,
	email       VARCHAR2 NOT NULL,
	password    VARCHAR2 NOT NULL,
	tel         VARCHAR2 NOT NULL,
	postcode    VARCHAR2 NOT NULL,
	home_addr   VARCHAR2 NOT NULL,
	detail_addr VARCHAR2,
	sex         VARCHAR2 NOT NULL,
	birth       VARCHAR2 NOT NULL,
	role        VARCHAR2 NOT NULL,
	CONSTRAINT PK_MEMBER_2 PRIMARY KEY (id)
);

ALTER TABLE HR.MEMBER_2
	ADD CONSTRAINT UQ_id UNIQUE (id);

ALTER TABLE HR.MEMBER_2
	ADD CONSTRAINT UQ_email UNIQUE (email);

COMMENT ON TABLE HR.MEMBER_2 IS '회원 테이블';

COMMENT ON COLUMN HR.MEMBER_2.name IS '이름';

COMMENT ON COLUMN HR.MEMBER_2.id IS '아이디';

COMMENT ON COLUMN HR.MEMBER_2.email IS '이메일';

COMMENT ON COLUMN HR.MEMBER_2.password IS '비밀번호';

COMMENT ON COLUMN HR.MEMBER_2.tel IS '전화번호';

COMMENT ON COLUMN HR.MEMBER_2.postcode IS '우편번호';

COMMENT ON COLUMN HR.MEMBER_2.home_addr IS '기본 주소';

COMMENT ON COLUMN HR.MEMBER_2.detail_addr IS '상세주소';

COMMENT ON COLUMN HR.MEMBER_2.sex IS '성별';

COMMENT ON COLUMN HR.MEMBER_2.birth IS '생년월일';

COMMENT ON COLUMN HR.MEMBER_2.role IS '권한';

CREATE TABLE HR.CART_2
(
	cno NUMBER   NOT NULL,
	id  VARCHAR2 NOT NULL,
	CONSTRAINT PK_CART_2 PRIMARY KEY (cno)
);

COMMENT ON TABLE HR.CART_2 IS '장바구니 테이블';

COMMENT ON COLUMN HR.CART_2.cno IS '기본키';

COMMENT ON COLUMN HR.CART_2.id IS '외래키(회원 테이블 참조)';

CREATE TABLE HR.CART_ITEM_2
(
	cino     NUMBER   NOT NULL,
	image    VARCHAR2 NOT NULL,
	name     VARCHAR2 NOT NULL,
	price    NUMBER   NOT NULL,
	quantity NUMBER   NOT NULL,
	cno      NUMBER   NOT NULL,
	ino      NUMBER   NOT NULL,
	CONSTRAINT PK_CART_ITEM_2 PRIMARY KEY (cino)
);

COMMENT ON TABLE HR.CART_ITEM_2 IS '장바구니 상품 테이블';

COMMENT ON COLUMN HR.CART_ITEM_2.cino IS '기본키';

COMMENT ON COLUMN HR.CART_ITEM_2.image IS '상품 이미지';

COMMENT ON COLUMN HR.CART_ITEM_2.name IS '상품 이름';

COMMENT ON COLUMN HR.CART_ITEM_2.price IS '상품 가격';

COMMENT ON COLUMN HR.CART_ITEM_2.quantity IS '상품 수량';

COMMENT ON COLUMN HR.CART_ITEM_2.cno IS '외래키(장바구니 테이블 참조)';

COMMENT ON COLUMN HR.CART_ITEM_2.ino IS '외래키(상품 테이플 참조)';

CREATE TABLE HR.ORDER_2
(
	ono       NUMBER   NOT NULL,
	status    VARCHAR2 NOT NULL,
	payoption VARCHAR2 NOT NULL,
	price     NUMBER   NOT NULL,
	date      DATE     NOT NULL,
	id        VARCHAR2 NOT NULL,
	CONSTRAINT PK_ORDER_2 PRIMARY KEY (ono)
);

COMMENT ON TABLE HR.ORDER_2 IS '주문 테이블';

COMMENT ON COLUMN HR.ORDER_2.ono IS '기본키';

COMMENT ON COLUMN HR.ORDER_2.status IS '주문 상태';

COMMENT ON COLUMN HR.ORDER_2.payoption IS '결제 방법';

COMMENT ON COLUMN HR.ORDER_2.price IS '결제 금액';

COMMENT ON COLUMN HR.ORDER_2.date IS '결제일';

COMMENT ON COLUMN HR.ORDER_2.id IS '외래키(회원 테이블 참조)';

CREATE TABLE HR.DELEVERY_2
(
	code        VARCHAR2 NOT NULL,
	dno         NUMBER   NOT NULL,
	name        VARCHAR2 NOT NULL,
	tel         VARCHAR2 NOT NULL,
	postcode    VARCHAR2 NOT NULL,
	home_addr   VARCHAR2 NOT NULL,
	detail_addr VARCHAR2,
	ono         NUMBER   NOT NULL,
	CONSTRAINT PK_DELEVERY_2 PRIMARY KEY (dno)
);

COMMENT ON TABLE HR.DELEVERY_2 IS '배송 정보 테이블';

COMMENT ON COLUMN HR.DELEVERY_2.code IS '주문 코드';

COMMENT ON COLUMN HR.DELEVERY_2.dno IS '기본키';

COMMENT ON COLUMN HR.DELEVERY_2.name IS '회원 이름';

COMMENT ON COLUMN HR.DELEVERY_2.tel IS '회원 전화번호';

COMMENT ON COLUMN HR.DELEVERY_2.postcode IS '우편번호';

COMMENT ON COLUMN HR.DELEVERY_2.home_addr IS '기본주소';

COMMENT ON COLUMN HR.DELEVERY_2.detail_addr IS '상세주소';

COMMENT ON COLUMN HR.DELEVERY_2.ono IS '외래키(주문 테이블 참조)';

CREATE TABLE HR.NOTICE_2
(
	nno     NUMBER   NOT NULL,
	name    VARCHAR2 NOT NULL,
	title   VARCHAR2 NOT NULL,
	content CLOB     NOT NULL,
	regdate DATE     NOT NULL,
	hit     NUMBER   NOT NULL,
	CONSTRAINT PK_NOTICE_2 PRIMARY KEY (nno)
);

COMMENT ON TABLE HR.NOTICE_2 IS '공지사항 테이블';

COMMENT ON COLUMN HR.NOTICE_2.nno IS '기본키';

COMMENT ON COLUMN HR.NOTICE_2.name IS '작성자';

COMMENT ON COLUMN HR.NOTICE_2.title IS '제목';

COMMENT ON COLUMN HR.NOTICE_2.content IS '내용';

COMMENT ON COLUMN HR.NOTICE_2.regdate IS '작성일';

COMMENT ON COLUMN HR.NOTICE_2.hit IS '조회수';

CREATE TABLE HR.ORDER_ITEM_2
(
	oino     NUMBER   NOT NULL,
	image    VARCHAR2 NOT NULL,
	name     VARCHAR2 NOT NULL,
	price    NUMBER   NOT NULL,
	quantity NUMBER   NOT NULL,
	ono      NUMBER   NOT NULL,
	ino      NUMBER   NOT NULL,
	CONSTRAINT PK_ORDER_ITEM_2 PRIMARY KEY (oino)
);

COMMENT ON TABLE HR.ORDER_ITEM_2 IS '주문 상품 테이블';

COMMENT ON COLUMN HR.ORDER_ITEM_2.oino IS '기본키';

COMMENT ON COLUMN HR.ORDER_ITEM_2.image IS '상품 이미지';

COMMENT ON COLUMN HR.ORDER_ITEM_2.name IS '상품 이름';

COMMENT ON COLUMN HR.ORDER_ITEM_2.price IS '상품 가격';

COMMENT ON COLUMN HR.ORDER_ITEM_2.quantity IS '상품 수량';

COMMENT ON COLUMN HR.ORDER_ITEM_2.ono IS '외래키(주문 테이블 참조)';

COMMENT ON COLUMN HR.ORDER_ITEM_2.ino IS '외래키(상품 테이플 참조)';

CREATE TABLE HR.REPLY_2
(
	rno     NUMBER   NOT NULL,
	name    VARCHAR2 NOT NULL,
	content CLOB     NOT NULL,
	regdate DATE     NOT NULL,
	bno     NUMBER   NOT NULL,
	id      VARCHAR2 NOT NULL,
	CONSTRAINT PK_REPLY_2 PRIMARY KEY (rno)
);

COMMENT ON TABLE HR.REPLY_2 IS '댓글 테이블';

COMMENT ON COLUMN HR.REPLY_2.rno IS '기본키';

COMMENT ON COLUMN HR.REPLY_2.name IS '작성자';

COMMENT ON COLUMN HR.REPLY_2.content IS '내용';

COMMENT ON COLUMN HR.REPLY_2.regdate IS '작성일';

COMMENT ON COLUMN HR.REPLY_2.bno IS '외래키(게시글 테이블 참조)';

COMMENT ON COLUMN HR.REPLY_2.id IS '외래키(회원 테이블 참조)';

CREATE TABLE HR.BOARD_2
(
	bno     NUMBER   NOT NULL,
	name    VARCHAR2 NOT NULL,
	subject VARCHAR2 NOT NULL,
	content CLOB     NOT NULL,
	regdate DATE     NOT NULL,
	hit     NUMBER   NOT NULL,
	id      VARCHAR2 NOT NULL,
	CONSTRAINT PK_BOARD_2 PRIMARY KEY (bno)
);

COMMENT ON TABLE HR.BOARD_2 IS '게시글 테이블';

COMMENT ON COLUMN HR.BOARD_2.bno IS '기본키';

COMMENT ON COLUMN HR.BOARD_2.name IS '작성자';

COMMENT ON COLUMN HR.BOARD_2.subject IS '제목';

COMMENT ON COLUMN HR.BOARD_2.content IS '내용';

COMMENT ON COLUMN HR.BOARD_2.regdate IS '작성일';

COMMENT ON COLUMN HR.BOARD_2.hit IS '조회수';

COMMENT ON COLUMN HR.BOARD_2.id IS '외래키(회원 테이블 참조)';

CREATE TABLE HR.ITEM_REVIEW_2
(
	rno         NUMBER   NOT NULL,
	name        VARCHAR2 NOT NULL,
	comment     CLOB     NOT NULL,
	create_date DATE     NOT NULL,
	update_date DATE     NOT NULL,
	hit         NUMBER   NOT NULL,
	ino         NUMBER   NOT NULL,
	id          VARCHAR2 NOT NULL,
	CONSTRAINT PK_ITEM_REVIEW_2 PRIMARY KEY (rno)
);

COMMENT ON TABLE HR.ITEM_REVIEW_2 IS '상품 리뷰 테이블';

COMMENT ON COLUMN HR.ITEM_REVIEW_2.rno IS '기본키';

COMMENT ON COLUMN HR.ITEM_REVIEW_2.name IS '작성자';

COMMENT ON COLUMN HR.ITEM_REVIEW_2.comment IS '내용';

COMMENT ON COLUMN HR.ITEM_REVIEW_2.create_date IS '작성날짜';

COMMENT ON COLUMN HR.ITEM_REVIEW_2.update_date IS '수정날짜';

COMMENT ON COLUMN HR.ITEM_REVIEW_2.hit IS '조회수';

COMMENT ON COLUMN HR.ITEM_REVIEW_2.ino IS '외래키(상품 테이플 참조)';

COMMENT ON COLUMN HR.ITEM_REVIEW_2.id IS '외래키(회원 테이블 참조)';

CREATE TABLE HR.QA_2
(
	qano       NUMBER   NOT NULL,
	title      VARCHAR2 NOT NULL,
	comment    CLOB     NOT NULL,
	category   VARCHAR2 NOT NULL,
	password   VARCHAR2 NOT NULL,
	lock       VARCHAR2 NOT NULL,
	hit        NUMBER   NOT NULL,
	crate_date DATE     NOT NULL,
	ono        NUMBER   NOT NULL,
	ino        NUMBER   NOT NULL,
	id         VARCHAR2 NOT NULL,
	CONSTRAINT PK_QA_2 PRIMARY KEY (qano)
);

COMMENT ON TABLE HR.QA_2 IS '문의사항 테이블';

COMMENT ON COLUMN HR.QA_2.qano IS '기본키';

COMMENT ON COLUMN HR.QA_2.title IS '제목';

COMMENT ON COLUMN HR.QA_2.comment IS '내용';

COMMENT ON COLUMN HR.QA_2.category IS '문의사항 구분(상품 | 배송)';

COMMENT ON COLUMN HR.QA_2.password IS '비밀블 비밀번호';

COMMENT ON COLUMN HR.QA_2.lock IS '글 잠금여부';

COMMENT ON COLUMN HR.QA_2.hit IS '조회수';

COMMENT ON COLUMN HR.QA_2.crate_date IS '작성일';

COMMENT ON COLUMN HR.QA_2.ono IS '외래키(주문 테이블 참조)';

COMMENT ON COLUMN HR.QA_2.ino IS '외래키(상품 테이플 참조)';

COMMENT ON COLUMN HR.QA_2.id IS '외래키(회원 테이블 참조)';

CREATE TABLE HR.ITEM_CATEGORY_2
(
	icno NUMBER   NOT NULL,
	name VARCHAR2 NOT NULL,
	CONSTRAINT PK_ITEM_CATEGORY_2 PRIMARY KEY (icno)
);

COMMENT ON TABLE HR.ITEM_CATEGORY_2 IS '상품 카테고리 테이블';

COMMENT ON COLUMN HR.ITEM_CATEGORY_2.icno IS ' 기본키';

COMMENT ON COLUMN HR.ITEM_CATEGORY_2.name IS '카테고리 이름';

CREATE TABLE HR.QA_REPLY_2
(
	qarno       NUMBER NOT NULL,
	comment     CLOB   NOT NULL,
	create_date DATE   NOT NULL,
	hit         NUMBER NOT NULL,
	qano        NUMBER NOT NULL,
	CONSTRAINT PK_QA_REPLY_2 PRIMARY KEY (qarno)
);

COMMENT ON TABLE HR.QA_REPLY_2 IS '문의사항 댓글 테이블';

COMMENT ON COLUMN HR.QA_REPLY_2.qarno IS '기본키';

COMMENT ON COLUMN HR.QA_REPLY_2.comment IS '내용';

COMMENT ON COLUMN HR.QA_REPLY_2.create_date IS '작성일';

COMMENT ON COLUMN HR.QA_REPLY_2.hit IS '조회수';

COMMENT ON COLUMN HR.QA_REPLY_2.qano IS '외래키(문의사항 테이블 참조)';

CREATE TABLE HR.ITEM_LIKE_2
(
	lno   NUMBER   NOT NULL,
	image VARCHAR2 NOT NULL,
	name  VARCHAR2 NOT NULL,
	price NUMBER   NOT NULL,
	ino   NUMBER   NOT NULL,
	CONSTRAINT PK_ITEM_LIKE_2 PRIMARY KEY (lno)
);

COMMENT ON TABLE HR.ITEM_LIKE_2 IS '좋아요 테이블';

COMMENT ON COLUMN HR.ITEM_LIKE_2.lno IS '기본키';

COMMENT ON COLUMN HR.ITEM_LIKE_2.image IS '상품 이미지';

COMMENT ON COLUMN HR.ITEM_LIKE_2.name IS '상품 이름';

COMMENT ON COLUMN HR.ITEM_LIKE_2.price IS '상품 가격';

COMMENT ON COLUMN HR.ITEM_LIKE_2.ino IS '외래키(상품 테이플 참조)';

CREATE TABLE HR.CAMP_2
(
	cno    NUMBER   NOT NULL,
	image  VARCHAR2 NOT NULL,
	tel    VARCHAR2 NOT NULL,
	type   VARCHAR2 NOT NULL,
	page   VARCHAR2 NOT NULL,
	period VARCHAR2 NOT NULL,
	date   DATE     NOT NULL,
	hit    NUMBER   NOT NULL,
	CONSTRAINT PK_CAMP_2 PRIMARY KEY (cno)
);

COMMENT ON TABLE HR.CAMP_2 IS '캠핑장 테이블';

COMMENT ON COLUMN HR.CAMP_2.cno IS '기본키';

COMMENT ON COLUMN HR.CAMP_2.image IS '캠핑장 이미지';

COMMENT ON COLUMN HR.CAMP_2.tel IS '캠핑장 전화번호';

COMMENT ON COLUMN HR.CAMP_2.type IS '캠핑장 유형';

COMMENT ON COLUMN HR.CAMP_2.page IS '캠핑장 홈페이지';

COMMENT ON COLUMN HR.CAMP_2.period IS '운영기간';

COMMENT ON COLUMN HR.CAMP_2.date IS '운영일';

COMMENT ON COLUMN HR.CAMP_2.hit IS '조회수';

CREATE TABLE HR.CAMP_LIKE_2
(
	clno  NUMBER   NOT NULL,
	image VARCHAR2 NOT NULL,
	name  VARCHAR2 NOT NULL,
	cno   NUMBER   NOT NULL,
	id    VARCHAR2 NOT NULL,
	CONSTRAINT PK_CAMP_LIKE_2 PRIMARY KEY (clno)
);

COMMENT ON TABLE HR.CAMP_LIKE_2 IS '캠핑장 좋아요 테이블';

COMMENT ON COLUMN HR.CAMP_LIKE_2.clno IS '기본키';

COMMENT ON COLUMN HR.CAMP_LIKE_2.image IS '캠핑장 이미지';

COMMENT ON COLUMN HR.CAMP_LIKE_2.name IS '캠핑장 이름';

COMMENT ON COLUMN HR.CAMP_LIKE_2.cno IS '외래키(캠핑장 테이블 참조)';

COMMENT ON COLUMN HR.CAMP_LIKE_2.id IS '외래키(회원 테이블 참조)';

CREATE TABLE HR.CAMP_REVIEW_2
(
	crno    NUMBER   NOT NULL,
	name    VARCHAR2 NOT NULL,
	content CLOB     NOT NULL,
	regdate DATE     NOT NULL,
	cno     NUMBER   NOT NULL,
	id      VARCHAR2 NOT NULL,
	CONSTRAINT PK_CAMP_REVIEW_2 PRIMARY KEY (crno)
);

COMMENT ON TABLE HR.CAMP_REVIEW_2 IS '캠핑장 리뷰 테이블';

COMMENT ON COLUMN HR.CAMP_REVIEW_2.crno IS '기본키';

COMMENT ON COLUMN HR.CAMP_REVIEW_2.name IS '작성자';

COMMENT ON COLUMN HR.CAMP_REVIEW_2.content IS '내용';

COMMENT ON COLUMN HR.CAMP_REVIEW_2.regdate IS '작성일';

COMMENT ON COLUMN HR.CAMP_REVIEW_2.cno IS '외래키(캠핑장 테이블 참조)';

COMMENT ON COLUMN HR.CAMP_REVIEW_2.id IS '외래키(회원 테이블 참조)';

CREATE TABLE HR.NOTICE_IMAGE_2
(
	nino NUMBER   NOT NULL,
	path VARCHAR2 NOT NULL,
	name VARCHAR2 NOT NULL,
	size VARCHAR2 NOT NULL,
	nno  NUMBER   NOT NULL,
	CONSTRAINT PK_NOTICE_IMAGE_2 PRIMARY KEY (nino)
);

COMMENT ON TABLE HR.NOTICE_IMAGE_2 IS '공지사항 이미지 테이블';

COMMENT ON COLUMN HR.NOTICE_IMAGE_2.nino IS '기본키';

COMMENT ON COLUMN HR.NOTICE_IMAGE_2.path IS '경로';

COMMENT ON COLUMN HR.NOTICE_IMAGE_2.name IS '파일명';

COMMENT ON COLUMN HR.NOTICE_IMAGE_2.size IS '파일크키';

COMMENT ON COLUMN HR.NOTICE_IMAGE_2.nno IS '외래키(공지사항 테이블 참조)';

CREATE TABLE HR.ITEM_2
(
	ino            NUMBER   NOT NULL,
	image          VARCHAR2 NOT NULL,
	name           VARCHAR2 NOT NULL,
	price          NUMBER   NOT NULL,
	description    CLOB     NOT NULL,
	stock          NUMBER   NOT NULL,
	status         VARCHAR2 NOT NULL,
	discount       NUMBER   NOT NULL,
	delivery_price NUMBER   NOT NULL,
	like_cnt       NUMBER   NOT NULL,
	jjim_cnt       NUMBER   NOT NULL,
	icno           NUMBER   NOT NULL,
	CONSTRAINT PK_ITEM_2 PRIMARY KEY (ino)
);

COMMENT ON TABLE HR.ITEM_2 IS '상품 테이블';

COMMENT ON COLUMN HR.ITEM_2.ino IS '기본키';

COMMENT ON COLUMN HR.ITEM_2.image IS '상품이미지';

COMMENT ON COLUMN HR.ITEM_2.name IS '상품이름';

COMMENT ON COLUMN HR.ITEM_2.price IS '상품 가격';

COMMENT ON COLUMN HR.ITEM_2.description IS '상품 상세';

COMMENT ON COLUMN HR.ITEM_2.stock IS '상품 재고';

COMMENT ON COLUMN HR.ITEM_2.status IS '상품 상태';

COMMENT ON COLUMN HR.ITEM_2.discount IS '상품 할인율';

COMMENT ON COLUMN HR.ITEM_2.delivery_price IS '상품 배송비';

COMMENT ON COLUMN HR.ITEM_2.like_cnt IS '좋아요 개수';

COMMENT ON COLUMN HR.ITEM_2.jjim_cnt IS '찜 개수';

COMMENT ON COLUMN HR.ITEM_2.icno IS ' 외래키(상품테이블 참조)';

ALTER TABLE HR.CART_ITEM_2
	ADD CONSTRAINT FK_CART_2_TO_CART_ITEM_2
		FOREIGN KEY (cno)
		REFERENCES HR.CART_2 (cno);

ALTER TABLE HR.DELEVERY_2
	ADD CONSTRAINT FK_ORDER_2_TO_DELEVERY_2
		FOREIGN KEY (ono)
		REFERENCES HR.ORDER_2 (ono);

ALTER TABLE HR.ORDER_ITEM_2
	ADD CONSTRAINT FK_ORDER_2_TO_ORDER_ITEM_2
		FOREIGN KEY (ono)
		REFERENCES HR.ORDER_2 (ono);

ALTER TABLE HR.REPLY_2
	ADD CONSTRAINT FK_BOARD_2_TO_REPLY_2
		FOREIGN KEY (bno)
		REFERENCES HR.BOARD_2 (bno);

ALTER TABLE HR.QA_REPLY_2
	ADD CONSTRAINT FK_QA_2_TO_QA_REPLY_2
		FOREIGN KEY (qano)
		REFERENCES HR.QA_2 (qano);

ALTER TABLE HR.CAMP_LIKE_2
	ADD CONSTRAINT FK_CAMP_2_TO_CAMP_LIKE_2
		FOREIGN KEY (cno)
		REFERENCES HR.CAMP_2 (cno);

ALTER TABLE HR.CAMP_REVIEW_2
	ADD CONSTRAINT FK_CAMP_2_TO_CAMP_REVIEW_2
		FOREIGN KEY (cno)
		REFERENCES HR.CAMP_2 (cno);

ALTER TABLE HR.NOTICE_IMAGE_2
	ADD CONSTRAINT FK_NOTICE_2_TO_NOTICE_IMAGE_2
		FOREIGN KEY (nno)
		REFERENCES HR.NOTICE_2 (nno);

ALTER TABLE HR.QA_2
	ADD CONSTRAINT FK_ORDER_2_TO_QA_2
		FOREIGN KEY (ono)
		REFERENCES HR.ORDER_2 (ono);

ALTER TABLE HR.QA_2
	ADD CONSTRAINT FK_ITEM_2_TO_QA_2
		FOREIGN KEY (ino)
		REFERENCES HR.ITEM_2 (ino);

ALTER TABLE HR.ITEM_LIKE_2
	ADD CONSTRAINT FK_ITEM_2_TO_ITEM_LIKE_2
		FOREIGN KEY (ino)
		REFERENCES HR.ITEM_2 (ino);

ALTER TABLE HR.ITEM_REVIEW_2
	ADD CONSTRAINT FK_ITEM_2_TO_ITEM_REVIEW_2
		FOREIGN KEY (ino)
		REFERENCES HR.ITEM_2 (ino);

ALTER TABLE HR.CART_ITEM_2
	ADD CONSTRAINT FK_ITEM_2_TO_CART_ITEM_2
		FOREIGN KEY (ino)
		REFERENCES HR.ITEM_2 (ino);

ALTER TABLE HR.ITEM_2
	ADD CONSTRAINT FK_ITEM_CATEGORY_2_TO_ITEM_2
		FOREIGN KEY (icno)
		REFERENCES HR.ITEM_CATEGORY_2 (icno);

ALTER TABLE HR.ORDER_ITEM_2
	ADD CONSTRAINT FK_ITEM_2_TO_ORDER_ITEM_2
		FOREIGN KEY (ino)
		REFERENCES HR.ITEM_2 (ino);

ALTER TABLE HR.ITEM_REVIEW_2
	ADD CONSTRAINT FK_MEMBER_2_TO_ITEM_REVIEW_2
		FOREIGN KEY (id)
		REFERENCES HR.MEMBER_2 (id);

ALTER TABLE HR.CART_2
	ADD CONSTRAINT FK_MEMBER_2_TO_CART_2
		FOREIGN KEY (id)
		REFERENCES HR.MEMBER_2 (id);

ALTER TABLE HR.CAMP_REVIEW_2
	ADD CONSTRAINT FK_MEMBER_2_TO_CAMP_REVIEW_2
		FOREIGN KEY (id)
		REFERENCES HR.MEMBER_2 (id);

ALTER TABLE HR.BOARD_2
	ADD CONSTRAINT FK_MEMBER_2_TO_BOARD_2
		FOREIGN KEY (id)
		REFERENCES HR.MEMBER_2 (id);

ALTER TABLE HR.REPLY_2
	ADD CONSTRAINT FK_MEMBER_2_TO_REPLY_2
		FOREIGN KEY (id)
		REFERENCES HR.MEMBER_2 (id);

ALTER TABLE HR.ORDER_2
	ADD CONSTRAINT FK_MEMBER_2_TO_ORDER_2
		FOREIGN KEY (id)
		REFERENCES HR.MEMBER_2 (id);

ALTER TABLE HR.QA_2
	ADD CONSTRAINT FK_MEMBER_2_TO_QA_2
		FOREIGN KEY (id)
		REFERENCES HR.MEMBER_2 (id);

ALTER TABLE HR.CAMP_LIKE_2
	ADD CONSTRAINT FK_MEMBER_2_TO_CAMP_LIKE_2
		FOREIGN KEY (id)
		REFERENCES HR.MEMBER_2 (id);
